---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: blog-admin:apps/Deployment:default/blog-admin
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"blog-admin:apps/Deployment:default/blog-admin"},"name":"blog-admin","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"blog-admin"}},"template":{"metadata":{"labels":{"app":"blog-admin"}},"spec":{"containers":[{"image":"chouqe/blog-admin-frontend:latest","imagePullPolicy":"Always","name":"frontend","ports":[{"containerPort":80}]}]}}}}
    name: blog-admin
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: blog-admin
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-10T16:47:42+03:00"
        labels:
          app: blog-admin
      spec:
        containers:
        - image: chouqe/blog-admin-frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      deployment.kubernetes.io/revision: "30"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"blog-api:apps/Deployment:default/blog-api"},"name":"blog-api","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"blog-api"}},"template":{"metadata":{"labels":{"app":"blog-api"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"blog-api-config"}},{"secretRef":{"name":"blog-api-secrets"}}],"image":"chouqe/blog-api-application:latest","livenessProbe":{"httpGet":{"path":"/api/v1/categories/","port":7070},"initialDelaySeconds":15,"periodSeconds":20},"name":"application","ports":[{"containerPort":7070}],"readinessProbe":{"httpGet":{"path":"/api/v1/categories/","port":7070},"initialDelaySeconds":5,"periodSeconds":10},"volumeMounts":[{"mountPath":"/project/logs","name":"logs"}]},{"args":["run","--server.http.listen-addr=0.0.0.0:8989","/etc/alloy/config.alloy"],"image":"grafana/alloy:latest","name":"alloy","volumeMounts":[{"mountPath":"/etc/alloy","name":"alloy-conf"},{"mountPath":"/project/logs","name":"logs"}]}],"volumes":[{"emptyDir":{},"name":"logs"},{"configMap":{"name":"alloy-config-blog"},"name":"alloy-conf"}]}}}}
    name: blog-api
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: blog-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-20T22:53:01+03:00"
        labels:
          app: blog-api
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: blog-api-config
          - secretRef:
              name: blog-api-secrets
          image: chouqe/blog-api-application:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/categories/
              port: 7070
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: application
          ports:
          - containerPort: 7070
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/categories/
              port: 7070
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /project/logs
            name: logs
        - args:
          - run
          - --server.http.listen-addr=0.0.0.0:8989
          - /etc/alloy/config.alloy
          image: grafana/alloy:latest
          imagePullPolicy: Always
          name: alloy
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/alloy
            name: alloy-conf
          - mountPath: /project/logs
            name: logs
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: logs
        - configMap:
            defaultMode: 420
            name: alloy-config-blog
          name: alloy-conf
      message: ReplicaSet "blog-api-7cb6c86cfb" has successfully progressed.
      reason: NewReplicaSetAvailable
      deployment.kubernetes.io/revision: "12"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"infrastructure-apps:apps/Deployment:default/minio"},"name":"minio","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"minio"}},"template":{"metadata":{"labels":{"app":"minio"}},"spec":{"containers":[{"args":["server","/data","--console-address",":9001"],"env":[{"name":"MINIO_ROOT_USER","value":"minioadmin"},{"name":"MINIO_ROOT_PASSWORD","value":"minio123"},{"name":"MINIO_BROWSER","value":"on"},{"name":"MINIO_CONSOLE_ADDRESS","value":":9001"},{"name":"MINIO_SERVER_URL","value":"https://minio.prof-stankin.ru"}],"image":"minio/minio:latest","name":"minio","ports":[{"containerPort":9000},{"containerPort":9001}],"volumeMounts":[{"mountPath":"/data","name":"minio-data"}]}],"volumes":[{"hostPath":{"path":"/var/lib/minio","type":"DirectoryOrCreate"},"name":"minio-data"}]}}}}
    name: minio
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: minio
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-18T18:37:06+03:00"
        labels:
          app: minio
      spec:
        containers:
        - args:
          - server
          - /data
          - --console-address
          - :9001
          env:
          - name: MINIO_ROOT_USER
            value: minioadmin
          - name: MINIO_ROOT_PASSWORD
            value: minio123
          - name: MINIO_BROWSER
            value: "on"
          - name: MINIO_CONSOLE_ADDRESS
            value: :9001
          - name: MINIO_SERVER_URL
            value: https://minio.prof-stankin.ru
          image: minio/minio:latest
          imagePullPolicy: Always
          name: minio
          ports:
          - containerPort: 9000
            protocol: TCP
          - containerPort: 9001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
